FROM python:3.12-slim

# Install dependencies
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ml_src/ ./ml_src
COPY conf/ ./conf

CMD ["python3", "ml_src/train.py"]
